# Generated by Django 5.1.7 on 2025-04-05 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('calcium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('iron', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('potassium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('Cholesterol', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'food',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('servings', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'user',
                'ordering': ['Username'],
            },
        ),
        migrations.CreateModel(
            name='recipe_ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodTracker.food')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodTracker.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredient',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='food_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodTracker.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodTracker.user')),
            ],
            options={
                'db_table': 'food_log',
                'ordering': ['date'],
            },
        ),
    ]
