# Generated by Django 5.2 on 2025-06-08 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_log',
            name='quantity',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
