# Generated by Django 5.1.7 on 2025-04-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Cholesterol',
            new_name='cholesterol',
        ),
    ]
