# Generated by Django 5.2 on 2025-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0002_food_log_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_log',
            name='cutritions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
