# Generated by Django 5.1.7 on 2025-04-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0002_rename_cholesterol_food_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
