# Generated by Django 5.2 on 2025-06-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0003_food_log_cutritions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_log',
            old_name='cutritions',
            new_name='nutritions',
        ),
    ]
