# Generated by Django 5.2 on 2025-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0004_rename_cutritions_food_log_nutritions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/default.jpg', null=True, upload_to='recipes/'),
        ),
    ]
