# Generated by Django 5.2 on 2025-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTracker', '0005_recipe_description_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipe_images/default.jpg', null=True, upload_to='recipe_images/'),
        ),
    ]
